version: '3.8'

services:
  rss-summarizer:
    build: .
    container_name: rss-summarizer-app
    env_file:
      - .env
    volumes:
      - ./rss:/app/rss
      - ./feeds.yml:/app/feeds.yml:ro
      - ./prompt.j2:/app/prompt.j2:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
